In [26]:
import pandas as pd

email_df = pd.read_csv("dataset/emails/SpamAssasin.csv")
email_df.dropna(inplace=True)
email_df = email_df[email_df['label'] % 2 == 0]
email_df

,sender,receiver,date,subject,body,label,urls
0,Robert Elz <kre@munnari.OZ.AU>,Chris Garrigues <cwg-dated-1030377287.06fa6d@D...,"Thu, 22 Aug 2002 18:26:25 +0700",Re: New Sequences Window,"Date: Wed, 21 Aug 2002 10:54:46 -0500 ...",0,1
1,Steve Burt <Steve_Burt@cursor-system.com>,"""'zzzzteana@yahoogroups.com'"" <zzzzteana@yahoo...","Thu, 22 Aug 2002 12:46:18 +0100",[zzzzteana] RE: Alexander,"Martin A posted:\nTassos Papadopoulos, the Gre...",0,1
2,"""Tim Chapman"" <timc@2ubh.com>",zzzzteana <zzzzteana@yahoogroups.com>,"Thu, 22 Aug 2002 13:52:38 +0100",[zzzzteana] Moscow bomber,Man Threatens Explosion In Moscow \n\nThursday...,0,1
3,Monty Solomon <monty@roscom.com>,undisclosed-recipient: ;,"Thu, 22 Aug 2002 09:15:25 -0400",[IRR] Klez: The Virus That Won't Die,Klez: The Virus That Won't Die\n \nAlready the...,0,1
4,Stewart Smith <Stewart.Smith@ee.ed.ac.uk>,zzzzteana@yahoogroups.com,"Thu, 22 Aug 2002 14:38:22 +0100",Re: [zzzzteana] Nothing like mama used to make,"> in adding cream to spaghetti carbonara, whi...",0,1
...,...,...,...,...,...,...,...
4086,"""Media Unspun"" <guterman@mediaunspun.imakenews...",zzz-unspun@example.com,"Thu, 26 Sep 2002 09:28:03 -0400",AOL Keyword: Fraud Probe,This is a multi-part message in MIME format......,0,1
4087,"""Ayn Rand Institute Media"" <davidh@aynrand.org>",<gazette@vineyard.net>,"Wed, 24 Jul 2002 11:09:22 -0700",GOVERNMENT REGULATION IS KILLING THE STOCK MARKET,PRESS RELEASE FROM THE AYN RAND INSTITUTE\n212...,0,1
4088,<isu@eircom.net>,social@linux.ie,"Sun, 29 Sep 2002 19:11:17 +0100",[ILUG-Social] Re: Important - reenactor insura...,My gut reaction would be to tell them to go an...,0,1
4089,"""Media Unspun"" <guterman@mediaunspun.imakenews...",zzz-unspun@example.com,"Tue, 01 Oct 2002 09:26:14 -0400",Market Can't Find Its Bottom With Both Hands,This is a multi-part message in MIME format......,0,1
4090,mailman-owner@lists.sourceforge.net,shiva+qpopper-webdev@sewingwitch.com,"Tue, 01 Oct 2002 17:08:10 -0700",(SPAM? 08.00) lists.sourceforge.net mailing li...,**********************************************...,0,1

In [27]:
email_dataset = pd.read_csv("dataset/emails/CEAS_08.csv")

email_dataset = pd.concat([email_dataset, email_df], axis=0, ignore_index=True)

email_dataset.dropna(inplace=True)

email_dataset.drop_duplicates()

email_dataset.to_csv("all_emails3.csv", index=False, encoding='utf-8')

email_dataset

,sender,receiver,date,subject,body,label,urls
0,Young Esposito <Young@iworld.de>,user4@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 16:31:02 -0700",Never agree to be a loser,"Buck up, your troubles caused by small dimensi...",1,1
1,Mok <ipline's1983@icable.ph>,user2.2@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 18:31:03 -0500",Befriend Jenna Jameson,\nUpgrade your sex and pleasures with these te...,1,1
2,Daily Top 10 <Karmandeep-opengevl@universalnet...,user2.9@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 20:28:00 -1200",CNN.com Daily Top 10,>+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+...,1,1
3,Michael Parker <ivqrnai@pobox.com>,SpamAssassin Dev <xrh@spamassassin.apache.org>,"Tue, 05 Aug 2008 17:31:20 -0600",Re: svn commit: r619753 - in /spamassassin/tru...,Would anyone object to removing .so from this ...,0,1
4,Gretchen Suggs <externalsep1@loanofficertool.com>,user2.2@gvc.ceas-challenge.cc,"Tue, 05 Aug 2008 19:31:21 -0400",SpecialPricesPharmMoreinfo,\nWelcomeFastShippingCustomerSupport\nhttp://7...,1,1
...,...,...,...,...,...,...,...
43073,"""Media Unspun"" <guterman@mediaunspun.imakenews...",zzz-unspun@example.com,"Thu, 26 Sep 2002 09:28:03 -0400",AOL Keyword: Fraud Probe,This is a multi-part message in MIME format......,0,1
43074,"""Ayn Rand Institute Media"" <davidh@aynrand.org>",<gazette@vineyard.net>,"Wed, 24 Jul 2002 11:09:22 -0700",GOVERNMENT REGULATION IS KILLING THE STOCK MARKET,PRESS RELEASE FROM THE AYN RAND INSTITUTE\n212...,0,1
43075,<isu@eircom.net>,social@linux.ie,"Sun, 29 Sep 2002 19:11:17 +0100",[ILUG-Social] Re: Important - reenactor insura...,My gut reaction would be to tell them to go an...,0,1
43076,"""Media Unspun"" <guterman@mediaunspun.imakenews...",zzz-unspun@example.com,"Tue, 01 Oct 2002 09:26:14 -0400",Market Can't Find Its Bottom With Both Hands,This is a multi-part message in MIME format......,0,1
43077,mailman-owner@lists.sourceforge.net,shiva+qpopper-webdev@sewingwitch.com,"Tue, 01 Oct 2002 17:08:10 -0700",(SPAM? 08.00) lists.sourceforge.net mailing li...,**********************************************...,0,1